server:
  port: 8093

spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: duang521


#mybatis-plush配置
mybatis-plus:
  #别名包  简化类型转化的写法
  type-aliases-package: com.jt.pojo
  #加载mybatis的映射文件
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  scan:
    basePackages: com.jt  #配置包扫描
  application:            #服务名称必须定义
    name: sso-provider
  registry:               #注册中心 backup代表备用
    address: zookeeper://192.168.1.11:2181?backup=192.168.1.11:2182,192.168.1.11:2183
  protocol:
    name: dubbo           #zookeeper节点名称
    port: 20880           #RPC通信 dubbo内部通信端口